/**
 * core/app.js — theme-agnostic generator shell with optional capabilities.
 */
const REGISTRY_URL='themes/registry.json';
const WEBHOOK_URL='backend/generate.php';
const AI_URL='backend/ai.php';
const els={
 topbar:document.getElementById('gTopbar'),changeThemeBtn:document.getElementById('gChangeThemeBtn'),myPagesBtn:document.getElementById('gMyPagesBtn'),themeSub:document.getElementById('gThemeSub'),selectScreen:document.getElementById('gSelectScreen'),themeGrid:document.getElementById('gThemeGrid'),themeSearch:document.getElementById('gThemeSearch'),themeCount:document.getElementById('gThemeCount'),workspace:document.getElementById('gWorkspace'),formMount:document.getElementById('gFormMount'),previewMock:document.getElementById('gPreviewMock'),pagesScreen:document.getElementById('gPagesScreen'),pagesMount:document.getElementById('gPagesMount')
};
let activeController=null,activeAiController=null,activeTheme=null,pagesController=null,allThemes=[];
init();
async function init(){
 els.changeThemeBtn.addEventListener('click',showThemeSelection);els.myPagesBtn.addEventListener('click',showMyPages);
 els.themeSearch.addEventListener('input',()=>renderThemeGrid(filterThemes(els.themeSearch.value)));
 await loadThemes();
}
async function loadThemes(){
 els.themeGrid.innerHTML='<div class="g-loading"><span class="g-spinner"></span> Loading themes…</div>';
 try{const res=await fetch(REGISTRY_URL,{cache:'no-store'});if(!res.ok)throw new Error('Theme registry request failed');const themes=await res.json();if(!Array.isArray(themes)||!themes.length)throw new Error('No themes available');allThemes=themes;renderThemeGrid(themes)}catch(err){els.themeGrid.innerHTML='<div class="g-error-card"><strong>Could not load themes</strong><span>Check that the generator is running from the project folder.</span><button type="button" id="gRetryThemes">Try again</button></div>';document.getElementById('gRetryThemes').addEventListener('click',loadThemes);console.error(err)}}
function filterThemes(query){const q=String(query||'').trim().toLowerCase();if(!q)return allThemes;return allThemes.filter(t=>[t.name,t.tagline,...(t.sections||[])].join(' ').toLowerCase().includes(q))}
function renderThemeGrid(themes){
 els.themeGrid.innerHTML='';els.themeCount.textContent=`${themes.length} theme${themes.length===1?'':'s'}`;
 if(!themes.length){els.themeGrid.innerHTML='<div class="g-empty"><strong>No matching themes</strong><span>Try a different search.</span></div>';return}
 themes.forEach(theme=>{const card=document.createElement('button');card.type='button';card.className='g-theme-card';card.setAttribute('aria-label',`Use ${theme.name} theme`);card.innerHTML=`<div class="g-card-body"><div class="g-card-top"><span class="g-theme-kicker">${escapeHtml((theme.sections||[])[0]||'THEME')}</span><span class="g-arrow" aria-hidden="true">↗</span></div><h3>${escapeHtml(theme.name)}</h3><p class="g-tagline">${escapeHtml(theme.tagline||'')}</p><div class="g-sections">${(theme.sections||[]).slice(0,5).map(s=>`<span>${escapeHtml(s)}</span>`).join('')}</div><div class="g-select-btn">Use this theme <span aria-hidden="true">→</span></div></div><img class="g-thumb" src="themes/${encodeURIComponent(theme.id)}/${theme.thumbnail||'thumbnail.svg'}" alt="${escapeHtml(theme.name)} preview" loading="lazy"/>`;card.addEventListener('click',()=>selectTheme(theme));els.themeGrid.appendChild(card)})
}
async function selectTheme(theme){
 activeTheme=theme;unmountPages();unmountAi();els.pagesScreen.classList.add('g-hidden');els.selectScreen.classList.add('g-hidden');els.workspace.classList.remove('g-hidden');els.topbar.classList.add('g-has-theme');els.themeSub.textContent=theme.name;els.formMount.innerHTML='<div class="g-loading"><span class="g-spinner"></span> Loading theme…</div>';renderPreviewEmpty();window.scrollTo({top:0,behavior:'smooth'});
 try{const mod=await import(`../themes/${theme.id}/form.js`);els.formMount.innerHTML='';activeController=await mod.mount(els.formMount,{themeId:theme.id,webhookUrl:WEBHOOK_URL});await mountOptionalAi(theme)}catch(err){els.formMount.innerHTML='<div class="g-error-card"><strong>This theme could not be loaded</strong><span>Please return to theme selection and try another theme.</span><button type="button" id="gRetryTheme">Back to themes</button></div>';document.getElementById('gRetryTheme').addEventListener('click',showThemeSelection);console.error(err);return}
 if(activeController&&typeof activeController.getPreviewSummary==='function'){refreshPreview();const debounced=debounce(refreshPreview,180);els.formMount.addEventListener('input',debounced);els.formMount.addEventListener('change',debounced)}else renderPreviewEmpty();
}
async function mountOptionalAi(theme){try{const mod=await import(`../themes/${theme.id}/ai.js`);if(typeof mod.mountAi!=='function')return;loadOptionalStylesheet(`themes/${theme.id}/ai.css`);activeAiController=await mod.mountAi(els.formMount,{themeId:theme.id,aiUrl:AI_URL})}catch(err){if(!/ai\.js|ai\.css|failed to fetch|module/i.test(String(err.message||err)))console.warn('Optional AI module failed:',err)}}
function loadOptionalStylesheet(href){if(document.querySelector(`link[data-optional-style="${href}"]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.dataset.optionalStyle=href;document.head.appendChild(link)}
function unmountAi(){if(activeAiController&&typeof activeAiController.unmount==='function')activeAiController.unmount();activeAiController=null}
function showThemeSelection(){if(activeController&&typeof activeController.unmount==='function')activeController.unmount();activeController=null;unmountAi();activeTheme=null;unmountPages();els.pagesScreen.classList.add('g-hidden');els.workspace.classList.add('g-hidden');els.selectScreen.classList.remove('g-hidden');els.topbar.classList.remove('g-has-theme');els.themeSub.textContent='Choose a theme to get started';window.scrollTo({top:0,behavior:'smooth'});}
async function showMyPages(){if(activeController&&typeof activeController.unmount==='function')activeController.unmount();activeController=null;unmountAi();activeTheme=null;els.selectScreen.classList.add('g-hidden');els.workspace.classList.add('g-hidden');els.topbar.classList.remove('g-has-theme');els.pagesScreen.classList.remove('g-hidden');unmountPages();els.pagesMount.innerHTML='<div class="g-loading"><span class="g-spinner"></span> Loading your pages…</div>';try{const mod=await import('./pages.js');pagesController=mod.mount(els.pagesMount,{apiBase:WEBHOOK_URL.replace('generate.php','pages.php')})}catch(err){els.pagesMount.innerHTML='<div class="g-error-card"><strong>Could not load your landing pages</strong><span>Please try again.</span></div>';console.error(err)}window.scrollTo({top:0,behavior:'smooth'})}
function unmountPages(){if(pagesController&&typeof pagesController.unmount==='function')pagesController.unmount();pagesController=null}
function refreshPreview(){if(!activeController||typeof activeController.getPreviewSummary!=='function')return;try{renderPreviewFromSummary(activeController.getPreviewSummary())}catch(err){console.warn('Preview refresh failed',err)}}
function renderPreviewEmpty(){els.previewMock.innerHTML='<div class="pm-empty" style="padding:24px 16px;">Start filling in the form to see your page take shape here.</div>'}
function renderPreviewFromSummary(summary){const s=Object.assign({badge:'',title:'',subtitle:'',heroImage:null,colors:{primary:'#2b2f77',secondary:'#1c1e21'},rows:[],chips:[]},summary||{});const heroStyle=s.heroImage?`background-image:url('${String(s.heroImage).replace(/'/g,'%27')}');`:`background-color:${escapeCssColor(s.colors.secondary)};`;const rows=Array.isArray(s.rows)?s.rows.filter(r=>r&&r.value):[];const rowsHtml=rows.length?rows.map(r=>`<div class="pm-row"><span class="pm-k">${escapeHtml(r.label)}</span><span>${escapeHtml(String(r.value))}</span></div>`).join(''):'<div class="pm-empty">Your project details will appear here.</div>';const chips=Array.isArray(s.chips)?s.chips.filter(Boolean):[];const chipsHtml=chips.length?`<div class="pm-chips">${chips.map(c=>`<span>${escapeHtml(c)}</span>`).join('')}</div>`:'';els.previewMock.innerHTML=`<div class="pm-nav" style="background:${escapeCssColor(s.colors.secondary)};"><span>${escapeHtml(activeTheme?activeTheme.name:'')}</span><span style="opacity:.7;">MENU</span></div><div class="pm-hero" style="${heroStyle}"><div class="pm-overlay"></div><div class="pm-hero-inner">${s.badge?`<span class="pm-badge" style="background:${escapeCssColor(s.colors.primary)};">${escapeHtml(s.badge)}</span>`:''}<p class="pm-title">${escapeHtml(s.title||'Your project name')}</p><p class="pm-sub">${escapeHtml(s.subtitle||'Add a location or short description')}</p></div></div><div class="pm-body">${rowsHtml}${chipsHtml}</div>`}
function escapeCssColor(value){const color=String(value||'').trim();return/^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(color)?color:'#2b2f77'}
function debounce(fn,wait){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),wait)}}
function escapeHtml(str){return String(str??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
